server:
  port: 8080
spring:
  application:
    name: license
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/license
    password: 123123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update